name: Hadolint

on: [push]

jobs:
  hadolint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Run Hadolint
        uses: hadolint/hadolint-action@v1.5.0
